package com.example.fitcore.application.ui.theme

import androidx.compose.ui.graphics.Color

/*
 * This file defines the colour palette for the Fitcore mobile application.
 *
 * The values here were carefully chosen to mirror the look and feel of the
 * Fitcore web front‑end. The web uses a dark base with subtle green accents
 * and a hint of warm off‑white for text. To achieve a similar aesthetic
 * on mobile we define a handful of named colours instead of the default
 * purple/pink palette generated by Android Studio. See Theme.kt for how
 * these colours are applied throughout Material 3.
 */

// Primary accent colour used for buttons, highlights and interactive elements.
val GreenPrimary = Color(0xFF22C55E)

// Slightly darker variant of the primary accent used for hover/pressed states
// and as a container colour for cards that need a subtle tint.
val GreenSecondary = Color(0xFF16A34A)

// Dark green used as the main background for pages. This matches the
// gradients seen on the web login and dashboard screens【610871410387510†L0-L4】.
val DarkGreen = Color(0xFF1F3A26)

// Almost black surface colour used for cards and panels. Provides contrast
// against the background while still feeling rich and deep【610871410387510†L24-L33】.
val NightBlack = Color(0xFF0D0F0D)

// Warm off‑white used for primary text on dark backgrounds. Borrowed from
// the seashell colour in the existing Compose theme and the web styles【610871410387510†L106-L113】.
val Seashell = Color(0xFFFFF8F3)

// Muted green/grey used for secondary text and subtle outlines. This echoes
// the reseda green used on the web dashboard【661950462325948†L25-L34】.
val ResedaGreen = Color(0xFF7B896F)

// Optional light gradient colours if a light dashboard is ever needed. These
// values correspond to the background gradient on the web dashboard【661950462325948†L6-L20】.
val LightGradientStart = Color(0xFFF5F7FA)
val LightGradientEnd = Color(0xFFC3CFE2)